//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_PZ_3.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deals
    {
        public int ID_Deal { get; set; }
        public int EmployeeID { get; set; }
        public int ClientID { get; set; }
        public int Object { get; set; }
        public System.DateTime Deal_date { get; set; }
        public Nullable<decimal> Deal_amount { get; set; }
        public int OwnerID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Clients Clients1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Objects Objects { get; set; }
    }
}
