//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_PZ_3.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspections
    {
        public int ID_Inspection { get; set; }
        public int EmployeeID { get; set; }
        public int Object { get; set; }
        public System.DateTime Date { get; set; }
        public string Result { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
