//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_PZ_3.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Objects()
        {
            this.Deals = new HashSet<Deals>();
        }
    
        public int ID_Object { get; set; }
        public int TypeID { get; set; }
        public string Address { get; set; }
        public decimal Price { get; set; }
        public decimal Square { get; set; }
        public int Rooms { get; set; }
        public int Year_built { get; set; }
        public int OwnerID { get; set; }
        public int StatusID { get; set; }
        public int Floor { get; set; }
        public int Number_floor { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deals> Deals { get; set; }
        public virtual Object_type Object_type { get; set; }
        public virtual Status Status { get; set; }
    }
}
